# Generated by Django 3.2.3 on 2021-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(null=True, upload_to='media/team/%Y/%m/')),
                ('description', models.TextField()),
            ],
        ),
    ]
